version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: github_analysis
      POSTGRES_PASSWORD: github_analysis
      POSTGRES_DB: github_analysis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U github_analysis"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: