"""

Revision ID: c05b21796725
Revises:
Create Date: 2025-02-09 09:10:16.415567

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c05b21796725"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("github_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_id"),
    )
    op.create_table(
        "pr_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("github_id", sa.BigInteger(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("user_login", sa.String(), nullable=False),
        sa.Column("pr_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["pr_id"], ["pull_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_id"),
    )
    op.create_table(
        "pr_diffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("old_file_path", sa.String(), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum("ADD", "DELETE", "MODIFY", "RENAME", name="changetype"),
            nullable=False,
        ),
        sa.Column("pr_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["pr_id"], ["pull_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "diff_hunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("old_start", sa.Integer(), nullable=False),
        sa.Column("old_lines", sa.Integer(), nullable=False),
        sa.Column("new_start", sa.Integer(), nullable=False),
        sa.Column("new_lines", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("diff_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["diff_id"], ["pr_diffs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("diff_hunks")
    op.drop_table("pr_diffs")
    op.drop_table("pr_comments")
    op.drop_table("pull_requests")
    # ### end Alembic commands ###
